sudo: required

language: node_js

node_js:
  - "5"
  - "4"
  - "0.12"

services:
  - docker

env:
  DOCKER_VERSION: 1.11.0-0~trusty
  DOCKER_COMPOSE_VERSION: 1.7.1
  DEBUG: "navy:*"
  NAVY_DEBUG: "navy:*"

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # print versions
  - docker --version
  - docker-compose --version

before_script:
  # bootstrap packages
  - npm run bootstrap
  - npm run webpack-build
